### ISSUE TITLE
GenMap error

### ISSUE THREAD

**Issue by barefists** [bozimmerman/CoffeeMud#9]
Hi there,

I've been trying to create a GenMap for a small area, but after the map is created, trying to read it creates an "Oops!" response. I copied the output on the log for your opinion on the matter:

java.lang.NullPointerException
	at com.planet_ink.coffee_mud.Items.Basic.StdMap.executeMsg(StdMap.java:588)
	at com.planet_ink.coffee_mud.Locales.StdRoom$1.apply(StdRoom.java:874)
	at com.planet_ink.coffee_mud.Locales.StdRoom$1.apply(StdRoom.java:870)
	at com.planet_ink.coffee_mud.Locales.StdRoom.eachItem(StdRoom.java:2175)
	at com.planet_ink.coffee_mud.Locales.StdRoom.executeMsg(StdRoom.java:870)
	at com.planet_ink.coffee_mud.Locales.StdRoom.reallyReallySend(StdRoom.java:1546)
	at com.planet_ink.coffee_mud.Locales.StdRoom.reallySend(StdRoom.java:1552)
	at com.planet_ink.coffee_mud.Locales.StdRoom.send(StdRoom.java:1581)
	at com.planet_ink.coffee_mud.Commands.Read.read(Read.java:69)
	at com.planet_ink.coffee_mud.Commands.Read.execute(Read.java:106)
	at com.planet_ink.coffee_mud.MOBS.StdMOB.doCommand(StdMOB.java:1968)
	at com.planet_ink.coffee_mud.MOBS.StdMOB.dequeCommand(StdMOB.java:1893)
	at com.planet_ink.coffee_mud.MOBS.StdMOB.enqueCommand(StdMOB.java:2082)
	at com.planet_ink.coffee_mud.Common.DefaultSession.mainLoop(DefaultSession.java:2518)
	at com.planet_ink.coffee_mud.Common.DefaultSession.run(DefaultSession.java:2236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Thank you so much for your time!

Regards,
XM

**Comment by bozimmerman** [comment]
I think this is fixed for the next version.

**Comment by barefists** [comment]
Oh that's great. Thanks! :D

XM
